fix: (IAC-621) Update Ansible template files
sassoftware/viya4-iac-k8s pull request #22
Opened 2022-07-13 21:21 UTC by jarpat

## Changes
Fixes logic in the ansible template files for the cr, jump, and nfs vms, so if the user opts to not create one of those resources it no longer throws an error.

## Tests

## Scenario 1:

Set the create flags for all the external servers to true, I also opted to use static ips for these resources 
```
create_jump = true
create_nfs = true
create_cr = true
```

Resources were successfully created, both the inventory and ansible-vars.yaml template successfully rendered and saved to disk WITH the jump, nfs, and cr sections

## Scenario 2:

Set the create flags for all the external servers to false
```
create_jump = false
create_nfs = false
create_cr = false
```

Resources were not created as expected, and both the inventory and ansible-vars.yaml template successfully rendered and saved to disk WITHOUT the jump, nfs, and cr sections

## Scenario 3:

Ensure that the create flags are not in the tfvars (create_jump, create_nfs, create_cr) so that they fallback on the their default value of false

Resources were not created as expected, and both the inventory and ansible-vars.yaml template successfully rendered and saved to disk WITHOUT the jump, nfs, and cr sections

2022-07-13 21:25 UTC, thpang requested changes
These look good. What if I comment out the postgres_servers block and have no postgres server? I believe it'll also throw this error. Please check and update. Thx.

2022-07-14 14:02 UTC, jarpat commented
@thpang  commenting out the `postgres_servers` block and have no postgres server did not result in an issue. It defaults to an empty map which the conditionals in the template files is able to handle.

2022-07-14 16:12 UTC, riragh approved these changes
LGTM

2022-07-14 16:25 UTC, thpang approved these changes
LGTM

2022-07-14 16:37 UTC, merged