Use 'kubectl create' rather than 'kubectl apply' when creating calico resources
sassoftware/viya4-iac-k8s pull request #31
Opened 2022-08-22 17:38 UTC by AWSmith0216

New cluster creations are failing while installing the calico operator. Error is:

`"stderr": "The CustomResourceDefinition \"installations.operator.tigera.io\" is invalid: metadata.annotations: Too long: must have at most 262144 bytes"`

I don't know why I've just started seeing this; perhaps the CRD size has grown. 

The [calico docs](https://projectcalico.docs.tigera.io/getting-started/kubernetes/self-managed-onprem/onpremises#install-calico-with-kubernetes-api-datastore-50-nodes-or-less) indicate that 'kubectl create' should be used instead of 'kubectl apply'. The former avoids the creation of the 'last-applied-configuration' annotation, which is likely the problem here. I confirmed in my own environment that using 'kubectl create' yields a successfully created cluster.

2022-08-22 17:46 UTC, thpang commented
@sayeun we'll need to get someone to look at this one right away. The viya4-iac-k8s deployments are failing with the current code base. This should not need CLT testing. Need to be aware that if this is run a second time or with update there may be issue and the logic altered.

2022-08-22 18:22 UTC, thpang requested changes

2022-08-22 18:22 UTC, thpang commented on roles/kubernetes/cni/calico/tasks/main.yaml
>      - update
Need to remove the `update` target and create an update target just like the `install` with `kubectl replace` to accommodate what `kubectl apply` does. There is also a not in the operator for Calico that `kubectl create` must be used given the data content size. Here's a link to the change and the comment in the code base about this one: 

https://github.com/tigera/operator/blame/master/Makefile#L317-L320

2022-08-22 18:22 UTC, thpang commented on roles/kubernetes/cni/calico/tasks/main.yaml
>      - update
Same comment as above need to break these out into `install` -> `kubectl create` and `update` -> `kubectl replace`

2022-08-22 18:49 UTC, thpang commented on roles/kubernetes/cni/calico/tasks/main.yaml
>      - update
I am going to mark these as resolved. Right now the code base is not re-entrant with update so one has to run install then uninstall using the ./oss-k8s.sh script. We'll address the need for `replace` in the near future.

2022-08-22 18:52 UTC, thpang commented
This merge can take place as-is. We don't currently support the `update` target so this current fix will work fine.

2022-08-22 18:54 UTC, thpang commented on docs/CONFIG-VARS.md
> +cluster_version        | Kubernetes version | string | "1.22.10" | Valid values are listed here: [SAS Viya Supported Kubernetes Versions](https://go.documentation.sas.com/doc/en/itopscdc/default/itop
This is kinda frowned upon. The SAS links have very specific items that change per version so we try to find a more generic URL. But is acceptable for now.

2022-08-22 18:55 UTC, thpang submitted a review, later dismissed
LGTM

2022-08-22 20:08 UTC, jarpat approved these changes

2022-08-22 20:19 UTC, merged

2022-08-23 10:22 UTC, raphaelpoumarede commented
back from vacations, I hit the exact same error. Does it mean that release 1.1.0 is broken and that I need to pull the "main" branch to make the IaC run work ?
thanks!

2022-08-23 13:16 UTC, raphaelpoumarede commented
FYI the fix (replace "kubectl apply" with "kubectl create") also worked for me.