IAC-753 - Doc review
sassoftware/viya4-iac-k8s pull request #44
Opened 2022-11-04 18:43 UTC by supear

Edited docs in repo.

2022-11-04 18:53 UTC, thpang requested changes

2022-11-04 18:53 UTC, thpang commented on README.md
> +- (Optional) At least 1 machine to host a PostgreSQL server (for the SAS Infrastructure Data Server component) if you plan to use an external database server with your cluster.
Lines have an extra space or line ending. Please remove.

2022-11-04 18:53 UTC, thpang commented on README.md
> +
Line needs to be removed formatting corrected.

2022-11-04 18:53 UTC, thpang commented on README.md
> +Terraform scripts require variable definitions as input. Review the variables files and modify default values to meet your requirements.
Lines have an extra space or line ending. Please remove.

2022-11-04 18:53 UTC, thpang commented on README.md
> +In order to use this repository, modify the [inventory file](./examples/bare-metal/sample-inventory) to provide information about the machine targets for the SAS Viya deployment.
Lines have an extra space or line ending. Please remove.

2022-11-04 18:55 UTC, thpang commented
Added a few folks to also review. ;)

2022-11-08 18:33 UTC, thpang approved these changes

2022-11-08 19:07 UTC, jarpat approved these changes

2022-11-08 21:08 UTC, riragh approved these changes

2022-11-08 21:14 UTC, merged