2.0.0 - January 24, 2023
sassoftware/viya4-iac-k8s pull request #46
Opened 2023-01-05 13:25 UTC by thpang

- #25
- #37
- #47
- Update repo about text to mirror new SAS Viya Platform naming
- Addition of the `local-storage` storage class to support:
  - SingleStore
  - OpenSearch
- Load balancer enhancements
  - MetalLB support - Needed for SingleStore load balancer IP assignment
  - More flexible load balancer syntax
- Added metrics-server
- Enhance uninstall - One can now remove kubernetes and re-install as needed
- Kubernetes 1.26 support
  - Includes updated containerd packaging
  - Modifications to kubeadm configuration file for api adjustments.
- Ability to control CNI version
- Removal of auto update task and packages from OS
- Disabling of SWAP
- Several version updates
- Misc.

2023-01-05 16:16 UTC, supear requested changes
Was in a rush, but I think I caught the most salient issues.

2023-01-05 16:16 UTC, supear commented on CodingStandards.txt
> +All items are specific to a given element. Elements can be root level terraform
Elements can be root-level Terraform
files or module-level Terraform files.
<< Capitalize "Terraform" and "Git" everywhere, except for commands.

2023-01-05 16:16 UTC, supear commented on CodingStandards.txt
> +  - Variables defined live in the root variables.yaml file for that element.
Change all instances of "live in" and "live at" to "are stored in".

2023-01-05 16:16 UTC, supear commented on CodingStandards.txt
> +When coding has finished you must run the
When coding has completed, run the following command:

2023-01-05 16:16 UTC, supear commented on README.md
> +To learn about all phases and options of the SAS Viya deployment process, see [Getting Started with SAS Viya and Open Source Kubernetes](https://go.documentation.sas.com/doc/en/itopscdc/default/itops
in _SAS Viya Platform Operations_.

2023-01-05 16:16 UTC, supear commented on README.md
> +To learn about all phases and options of the SAS Viya deployment process, see [Getting Started with SAS Viya and Open Source Kubernetes](https://go.documentation.sas.com/doc/en/itopscdc/default/itops
options of the SAS Viya platform deployment process,

2023-01-05 16:16 UTC, supear commented on README.md
> +Once the resources are provisioned, use the [viya4-deployment](https://github.com/sassoftware/viya4-deployment) project to deploy SAS Viya in your cloud environment. For more information about SAS Vi
Once the resources are provisioned, use the [viya4-deployment](https://github.com/sassoftware/viya4-deployment) project to deploy the SAS Viya platform in your cloud environment. For more information about SAS Viya platform requirements and documentation for the deployment process, refer to [SAS Viya Platform Operations](https://go.documentation.sas.com/doc/en/itopscdc/default/itopswn/titlepage.htm).

2023-01-05 16:16 UTC, supear commented on README.md
> +This project helps you to automate the cluster-provisioning phase of SAS Viya deployment. It contains Terraform scripts to provision cloud infrastructure resources for VMware, and it contains Ansible
This project helps you to automate the cluster-provisioning phase of SAS Viya platform deployment.

2023-01-05 16:16 UTC, supear commented on README.md
> +In order to use this repository, modify the [inventory file](./examples/bare-metal/sample-inventory) to provide information about the machine targets for the SAS Viya deployment.
for the SAS Viya platform deployment.

2023-01-05 16:16 UTC, supear commented on examples/bare-metal/sample-ansible-vars.yaml
> +# NOTE: To support Single Store usage in the viya4-iac-k8s code base
SingleStore

2023-01-05 16:16 UTC, supear commented on roles/kubernetes/control_plane/init/primary/templates/kubeadm-config.j2
> +# Kubelet Configration : https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/
Kubelet Configuration

2023-01-05 16:16 UTC, supear commented on roles/kubernetes/loadbalancer/kube_vip/tasks/main.yaml
> +    - name: Apply kube-vip Cloud Provider config map
configMap

2023-01-05 16:16 UTC, supear commented on roles/kubernetes/loadbalancer/metallb/tasks/main.yaml
> +#       an implied localhost and this keeps the magic inventory_file
The usage and setting of the iac_inventory_dir variable
#       is only required if this task is run on localhost or on
#       an implied localhost, which prevents the magic inventory_file
#       and inventory_dir variables from having values.    << Does it *prevent* them from having values, or should it be "which means that the values for the magic inventory_file and inventory_dir variables are not used"?

2023-01-05 16:16 UTC, supear commented on roles/kubernetes/loadbalancer/metallb/tasks/main.yaml
> +- name: Setting up metallb loadbalancer
Take this advice or leave it, but it really should be "MetalLB" everywhere exc. for variables, of course.
Setting up  MetalLB load balancer

2023-01-05 16:16 UTC, supear commented on roles/systems/container_registry/harbor/tasks/main.yaml
> +- name: Remove all docker container, volumes, networks
Task to remove all Docker artifacts
- name: Remove all Docker containers, volumes, networks

2023-01-05 16:16 UTC, supear commented on roles/systems/container_registry/harbor/templates/harbor-https-gen.tmpl
> +# Copy cert and key into the cert folder on your harbor host
Harbor

2023-01-05 16:16 UTC, supear commented on templates/ansible/ansible-vars.yaml.tmpl
> +#   VIP IP                      : https://kube-vip.io/docs/installation/static/
VIP IP Address

2023-01-05 16:16 UTC, supear commented on templates/ansible/ansible-vars.yaml.tmpl
> +#  metallb address format  : https://metallb.universe.tf/configuration/#layer-2-configuration
MetalLB

2023-01-05 16:16 UTC, supear commented on roles/systems/common/tasks/main.yaml
> +- name: Install python and pip packages
Python and PIP

2023-01-05 16:16 UTC, supear commented on roles/systems/common/tasks/main.yaml
> +- name: Update alternatives for python and pip
Python and PIP

2023-01-05 16:16 UTC, supear commented on CodingStandards.txt
> +  Example directory structure and files following these standards:
Here is an example directory structure and files that follow these standards:

2023-01-05 16:16 UTC, supear commented on CodingStandards.txt
> +For Terraform related files the standards are:
For Terraform-related files, the

2023-01-05 17:56 UTC, thpang commented on README.md
> +This project helps you to automate the cluster-provisioning phase of SAS Viya deployment. It contains Terraform scripts to provision cloud infrastructure resources for VMware, and it contains Ansible
Are you suggesting that the other parts of this paragraph be removed? Not sure about the comment here.

2023-01-05 17:59 UTC, supear commented on README.md
> +This project helps you to automate the cluster-provisioning phase of SAS Viya deployment. It contains Terraform scripts to provision cloud infrastructure resources for VMware, and it contains Ansible
The change I'm suggesting is just to add the word "platform" for the renaming of SAS Viya to "SAS Viya platform" in that sentence. Everything else can stay the same.

2023-01-05 18:43 UTC, thpang commented on roles/kubernetes/loadbalancer/metallb/tasks/main.yaml
> +#       an implied localhost and this keeps the magic inventory_file
They are needed, but not provided. Hence the wording and your initial correction.

2023-01-05 18:50 UTC, thpang commented
@supear I have made updates based on your review comments. If you could take another pass. Thx so very much.

2023-01-05 20:28 UTC, supear commented on README.md
> +Once the resources are provisioned, use the [viya4-deployment](https://github.com/sassoftware/viya4-deployment) project to deploy SAS Viya in platform your cloud environment. For more information abo
SAS Viya in platform -> SAS Viya platform in

2023-01-05 20:29 UTC, supear submitted a review, later dismissed
Just saw one typo!

2023-01-12 17:39 UTC, thpang commented
@supear looking for the typo you reference. If you could point me to its location. Thx.

2023-01-13 14:09 UTC, dhoucgitter commented on Dockerfile
> +ARG TERRAFORM_VERSION=1.3.2
Does oss-k8s require features present in TF 1.3.2 or is that the version you've been using locally? The other providers still reference TF 1.0.0 in their Dockerfiles.

2023-01-13 14:28 UTC, dhoucgitter commented on Dockerfile
> +ARG TERRAFORM_VERSION=1.3.2
Just noticed that the Readme calls out TF 1.3.2 as required below.

2023-01-13 14:51 UTC, dhoucgitter commented on docs/REQUIREMENTS.md
> +| [Ubuntu 22.04 LTS](https://releases.ubuntu.com/22.04/) | You must have a user account and password with privileges that enable unprompted `sudo`. You must also have a shared "private/public" SSH ke
The Readme content lists Ubuntu 20.04 LTS and 22.04 LTS as being supported but this file says 22.04 LTS is required. Should 20.04 LTS be listed here also?

2023-01-13 14:58 UTC, dhoucgitter commented on docs/REQUIREMENTS.md
> +4. You will need to updated ANY transformer being used for the **OpenSearch** or **SingleStore** products to mirror these values. Using `local-storage` as the storage class and adjusting the storage
```suggestion
4. You will need to update ANY transformer being used for the **OpenSearch** or **SingleStore** products to mirror these values. Using `local-storage` as the storage class and adjusting the storage size to mirror the partition created for use.
```

2023-01-17 13:41 UTC, dhoucgitter approved these changes

2023-01-23 16:31 UTC, dhoucgitter commented on docs/CONFIG-VARS.md
> +1. If you enable `server_ssl` without defining either `server_ssl_cert_file` or `server_ssl_cert_file`, the system's default SSL certificate and key are used instead. By default, on Ubuntu systems we
```suggestion
1. If you enable `server_ssl` without defining either `server_ssl_cert_file` or `server_ssl_key_file`, the system's default SSL certificate and key are used instead. By default, on Ubuntu systems we create a copy of those files and name them `ssl-cert-sas-${PG_HOST}.pem` and `ssl-cert-sas-${PG_HOST}.key`.
```

2023-01-24 15:37 UTC, thpang commented on docs/CONFIG-VARS.md
> +1. If you enable `server_ssl` without defining either `server_ssl_cert_file` or `server_ssl_cert_file`, the system's default SSL certificate and key are used instead. By default, on Ubuntu systems we
Updated and pushing to staging.

2023-01-24 15:39 UTC, dhoucgitter approved these changes

2023-01-24 15:40 UTC, anthoday approved these changes

2023-01-24 15:44 UTC, dhoucgitter approved these changes

2023-01-24 15:52 UTC, merged