docs: (IAC-916) V4M monitoring and logging fails to install with open-source K8s because of the missing v4m SC
sassoftware/viya4-iac-k8s pull request #51
Opened 2023-03-13 22:01 UTC by dhoucgitter

# Changes
Adds required instructions for setting `V4M_STORAGECLASS` value to `local-storage` in ansible-vars.yaml when using [viya4-deployment](https://github.com/sassoftware/viya4-deployment.git) to deploy `cluster-logging` and `cluster-monitoring` applications.

2023-03-14 15:08 UTC, thpang requested changes

2023-03-14 15:08 UTC, thpang commented on docs/REQUIREMENTS.md
> +
Review comments in the JIRA and make updates accordingly here. Thx.

2023-03-14 15:34 UTC, dhoucgitter commented on docs/REQUIREMENTS.md
> +
Applied updates from Jira review comments. Ready for re-review.

2023-03-27 21:26 UTC, thpang approved these changes

2023-03-28 13:00 UTC, jarpat submitted a review, later dismissed

2023-03-28 14:51 UTC, riragh approved these changes

2023-03-28 16:29 UTC, thpang commented on docs/REQUIREMENTS.md
> +```
I would prefer to have all of the code in an easy snippet that folks could copy and paste into their ansible vars file for the deployment tooling. If needed we should provide guidance to these items after the snippet.

For example the snippet should look like:

```yaml
## 3rd Party
### Ingress Controller
INGRESS_NGINX_CONFIG:
  controller:
    service:
      externalTrafficPolicy: Cluster or Local # Refer to Load Balancer type table above
      # loadBalancerIP: <your static ip> # Assigns a specific IP for your loadBalancer
      loadBalancerSourceRanges: [] # Not supported on open source kubernetes - https://kubernetes.io/docs/reference/kubernetes-api/service-resources/service-v1/
      annotations:

### NFS Subdir External Provisioner - SAS default storage class
# Updates to support open source Kubernetes 
NFS_CLIENT_NAME: nfs-subdir-external-provisioner-sas

## Logging and Monitoring
V4M_STORAGECLASS = local-storage
```
**NOTE**: You must explicitly set the value for `V4M_STORAGECLASS` in your ansible-vars.yaml file as shown below to a pre-existing Storage Class (for example: `local-storage`) prior to installing `cluster-logging` or `cluster-monitoring` with [viya4-deployment](https://github.com/sassoftware/viya4-deployment.git).

This is much cleaner and easier for folks to use and digest.

2023-03-28 17:22 UTC, dhoucgitter commented on docs/REQUIREMENTS.md
> +```
@thpang, moved the snippet into the main one and adjusted the NOTE:, how's that look now?

2023-03-28 17:40 UTC, thpang approved these changes
Made a comment on the change, but approving.

2023-03-28 17:40 UTC, thpang commented on docs/REQUIREMENTS.md
> +
I myself would still call this out as a NOTE to draw attention to the item. But it's fine as is it right now. I'll approve.

2023-03-28 17:43 UTC, riragh approved these changes

2023-03-28 17:45 UTC, merged